<?php

namespace App\Parser;

use Symfony\Component\PropertyAccess\PropertyAccess;
use Symfony\Component\PropertyAccess\PropertyAccessor;

class ParserResult
{
    private array $response;
    private array $parserLogs;
    private PropertyAccessor $accessor;

    public function __construct(array $response)
    {
        $this->response = $response;
        $this->accessor = PropertyAccess::createPropertyAccessor();
        $this->parserLogs = array_map(function (array $entry): ParserLog {
            return new ParserLog($entry);
        }, $this->accessor->getValue($this->response, "[logs]"));
    }

    /**
     * Returns the status returned by the parser. It can be:
     * INVALID_ARGUMENTS
     * INTERNAL_SERVER_ERROR
     * SUCCESSFULLY_PARSED
     *
     * @return string
     */
    public function getStatus(): string
    {
        return $this->accessor->getValue($this->response, "[status]");
    }

    /**
     * Returns the logs generated by the parser.
     *
     * @see ParserLog
     * @return array
     */
    public function getLogs(): array
    {
        return $this->parserLogs;
    }

    public function toArray(): array
    {
        return $this->response;
    }

}