<?php

namespace App\Parser;

use Symfony\Component\PropertyAccess\PropertyAccess;
use Symfony\Component\PropertyAccess\PropertyAccessor;

class ParserLog
{
    private array $response;
    private PropertyAccessor $accessor;

    public function __construct(array $response)
    {
        $this->response = $response;
        $this->accessor = PropertyAccess::createPropertyAccessor();
    }

    /**
     * Returns the type of log. It can be:
     * DEBUG
     * INFO
     * ERROR
     * WARNING
     *
     * @return string
     */
    public function getType(): string
    {
        return $this->accessor->getValue($this->response, "[type]");
    }

    /**
     * Returns the message generated associated to this parser log.
     *
     * @return string
     */
    public function getMessage(): string
    {
        return $this->accessor->getValue($this->response, "[message]");
    }

    /**
     * Returns the line of the script where the log was generated.
     *
     * @return int
     */
    public function getLine(): int
    {
        return $this->accessor->getValue($this->response, "[line]");
    }

    /**
     * Returns the tip generated by the parser, if any.
     *
     * @return string
     */
    public function getTip(): ?string
    {
        return $this->accessor->getValue($this->response, "[tip]");
    }

    public function toArray(): array
    {
        return $this->response;
    }

}